source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '8.0'
# 引用框架
use_frameworks!
# ignore all warnings from all pods(注解)
inhibit_all_warnings!

target 'LBLaunchImageAdDemo' do    
    pod 'SDWebImage','~> 4.0.0'
    pod 'SDWebImage/GIF'
end

